name: Documentation

on:
  release:
    types: [published]

jobs:
  generate-docs:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Documentation
      run: sudo gem install jazzy && jazzy
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/