name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        sdk: [macosx, iphonesimulator, appletvsimulator]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v -Xswiftc "-swift-version" -Xswiftc 5 -Xswiftc "-sdk" -Xswiftc `xcrun --sdk ${sdk} --show-sdk-path`
      env:
        sdk: ${{ matrix.sdk }}