name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        include:
        - sdk: macosx
          target: x86_64-apple-macosx11.5
        - sdk: iphonesimulator
          target: x86_64-apple-ios15.0-simulator
        - sdk: appletvsimulator
          target: x86_64-apple-tvos15.0-simulator
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v -Xswiftc "-swift-version" -Xswiftc 5 -Xswiftc "-sdk" -Xswiftc `xcrun --sdk ${sdk} --show-sdk-path` -Xswiftc "-target" -Xswiftc "${target}"
      env:
        sdk: ${{ matrix.sdk }}
        target: ${{ matrix.target }}
        DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
