name: Documentation

on:
  release:
    types: [published]

jobs:
  generate-docs:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Documentation
      run: sudo gem install jazzy && jazzy -o build
    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build